#spring:
#  application:
#    name: notification-service
#  config:
#    import: "optional:configserver:http://localhost:8888"

spring:
  application:
    name: notification-service

  cloud:
    config:
      uri: http://config-server:8888

  config:
    import: "optional:configserver:http://config-server:8888"
